# https://github.com/entwico/semantic-release-drone

kind: pipeline
name: default

steps:
- name: semantic-release
  image: entwico/semantic-release
  settings:
    mode: release 
    version_file: .release-version 
    git_user_name:
      from_secret: user_name_jass
    git_user_email:
      from_secret: user_email_jass
    GL_TOKEN:
      from_secret:  jass_token

# EOF
