# https://github.com/entwico/semantic-release-drone

kind: pipeline
name: default

steps:
- name: semantic-release
  image: entwico/semantic-release
  settings:
    mode: release 
    version_file: .release-version 
    GIT_USER_NAME: drone_ci
    GIT_USER_EMAIL: project12_bot@example.com
    GL_TOKEN:
      from_secret:  bot12_token

# EOF
