# TESTE DRONE
# https://github.com/entwico/semantic-release-drone

kind: pipeline
name: default

steps:
- name: semantic-release
  image: entwico/semantic-release
  settings:
    # "release" means the actual release and "predict" means to generate the version in dry run to use it e.g. before build
    mode: release 
    # the file where the version will be persisted, defaults to .release-version
    version_file: .release-version 
    # semantic release committer name (git config user.name)
    git_user_name: project_12_bot 
    # semantic release committer email (git config user.email)
    git_user_email: project12_bot@example.com
    # semantic release token (for authentication)
    gitlab_token: 
      from_secret:  bot12_token
