# https://github.com/entwico/semantic-release-drone

kind: pipeline
name: default

steps:
- name: semantic-release
  image: entwico/semantic-release
  settings:
    mode: release 
    version_file: .release-version 
    GIT_USER_NAME: "Jorge Assunção"
    GIT_USER_EMAIL: "j.assuncao@oestedesign.pt"
    GL_TOKEN:
      from_secret:  jass2_token

# EOF


