# https://hackmd.io/@PenguinCho/Sk7ygIWfI

kind: pipeline
type: docker
name: drone-pipeline

steps:
  - name: build
    image: node:12.14.0-buster
    environment:
      # environment variables
      GIT_AUTHOR_NAME:
        from_secret: user_name_jass
      GIT_AUTHOR_EMAIL:
        from_secret: user_email_jass
      GIT_COMMITTER_NAME:
        from_secret: user_name_jass
      GIT_COMMITTER_EMAIL:
        from_secret: user_email_jass
      GITLAB_TOKEN:
        from_secret:  jass_token
      # other environment variables...
    commands:
      # npm install
      - npm i --silent
      # run semantic-release
      - npx semantic-release
    when:
      branch:
        - master

