# https://github.com/entwico/semantic-release-drone

kind: pipeline
name: default

steps:
- name: semantic-release
  image: entwico/semantic-release
  settings:
    mode: release 
    version_file: .release-version 
    git_user_name: drone_ci
    git_user_email: project12_bot@example.com
    gitlab_token:
      from_secret:  bot12_token
